image : guillaumewuip/node-gulp-bower-ruby

variables:
  http_proxy : "http://proxy-serveur.univ-nantes.prive:3128"
  https_proxy: "http://proxy-serveur.univ-nantes.prive:3128"
  CI: "true"

stages:
  - test

cache:
  untracked: true
  paths:
    - node_modules/
    - bower_components/
  key: "dependencies"

before_script:
  - npm install &>/dev/null
  - bower install &>/dev/null

lint:
  script:
    - gulp check
  stage: test
