image : guillaumewuip/node-gulp-bower-ruby

variables:
  http_proxy : "http://proxy-serveur.univ-nantes.prive:3128"
  https_proxy: "http://proxy-serveur.univ-nantes.prive:3128"

stages:
  - test

lint:
  cache:
    untracked: true
    paths:
      - node_modules/
      - bower_components/
    key: "dependencies"
  script:
    - npm install &>/dev/null
    - bower install &>/dev/null
    - gulp check
  stage: test
