image : guillaumewuip/node-gulp-bower-ruby

before_script:
  - npm install &>/dev/null
  - bower install &>/dev/null

cache:
  untracked: true
  paths:
    - bower_components/
    - node_modules/

lint:
  script:
    - gulp check
