image : guillaumewuip/node-gulp-bower-ruby

variables:
  http_proxy : "http://proxy-serveur.univ-nantes.prive:3128"
  https_proxy: "http://proxy-serveur.univ-nantes.prive:3128"
  CI: "true"

stages:
  - test
  - deploy

cache:
  untracked: true
  paths:
    - node_modules/
  key: "dependencies"

lint:
  before_script:
    - npm install
  script:
    - gulp check
  stage: test

pushToGithub:
    only:
      -  master
    stage: deploy
    script:
      - (git remote | grep github) || git remote add github $GITHUB_PROJECT
      - git push github master

