image : monostream/nodejs-gulp-bower

before_script:
    - apt-get update > /dev/null && apt-get install -y ruby_full > /dev/null
    - gem install scss_lint > /dev/null
    - npm install > /dev/null
    - bower install > /dev/null

lint:
  script:
    - gulp check
