image : guillaumewuip/node-gulp-bower-ruby

variables:
  http_proxy : "http://proxy-serveur.univ-nantes.prive:3128"
  https_proxy: "http://proxy-serveur.univ-nantes.prive:3128"
  CI: "true"

stages:
  - test
  - deploy

cache:
  untracked: true
  paths:
    - node_modules/
  key: "dependencies"

before_script:
  - npm install

lint:
  script:
    - gulp check
  stage: test

pushToGithub:
    only:
      -  master
    stage: deploy
    script:
      - echo git remote add github $GITHUB_PROJECT
      - git remote add github $GITHUB_PROJECT
      - echo git push github master
      - git push github master

