image : guillaumewuip/node-gulp-bower-ruby

before_script:
  - npm install &>/dev/null
  - bower install &>/dev/null

variables:
  http_proxy : "http://proxy-serveur.univ-nantes.prive:3128"
  https_proxy: "http://proxy-serveur.univ-nantes.prive:3128"

cache:
  untracked: true
  paths:
    - bower_components/
    - node_modules/

lint:
  script:
    - gulp check

