language: node_js
node_js:
- 7.7.2
env:
- CI=true
before_script:
- npm install -g gulp
script:
- gulp check
notifications:
  slack:
    secure: TN9H9w1TgLY+jvv2FAc/psnPiWPbyNfgU5IiMira2sL3OZTz8tCZnLZMu/ceibXVpR7o9eddTC26BbQgLNEaaCGSAuwcAfz5nbJudtIKSZouj/3Q3tZyuu78c3Z4/lj+1J8dLMR0NTR++J/3AeEXzYk17ueY4bYUbgrJ9wWJyA2ZA1OOT5A2TXu7hSugvOWIepCOlWxfnq2C5EAIkG950AMW+woH8fO9qXYW7Sf2dstdSAl59gcSpcfnfPILSdxRdn76vTcmp8aIBXyYBbmRbYDPASQMW28goPkD3aWRUF9frB1yUJLhFiSnGf0x7Ec8AtQ/y1vvGLcbwGv4R7C3ZJbExlkgC/vpQ+gF5mvKH6NUJvZWJbDlfLAH/SqZiPEkmja+YfN1MUkeS6LSGYcLMxHxzBN8CmS5ErhVfs7MuNpV5I1r/7ef6lAV1sewEP+FSXPlOvxOMOpCcrHQOXSoNI34D3b4IHsLcmhcQBoQTnSErRVsC7ts0VTZqZTMwDbHvdkadXCDOV1Tk++t+k2jEbDNI6/nCXmZ99k+EEZdnA1d3fR78H3BMoWjFq4N8RhAO1bKXAcg8ekeQxB/PqsTwtnI3A0dOWSLoU+Z80iGxMlGgekTDoqJvRSMDm2DqirA8azOlKAEVUQt6vgbypwj8a3Pch6O5QVaKJn2Z7h4fb0=
