title: Polywave
description:
baseurl: ""
url: "http://polywave.github.io.com"

incremental: true

exclude:
    - node_modules

# Build settings
markdown: kramdown

collections:
  podcasts:
    output: true
    permalink: /podcasts/:title

