---
title: Polywave
timezone: Europe/Paris
collections:
  podcasts:
    title: Podcasts
    output: true
    permalink: "/podcasts/:title"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: 
baseurl: 
url: http://polywave.github.io.com
incremental: true
exclude:
- node_modules
markdown: kramdown
