// ---------------------------------------
// StreamInfoRadionomy
// v0.0.2 - 2016-11-17
//
// Available at:
// www.wimpyplayer.com
//
// Documentation:
// http://www.wimpyplayer.com/docs/streaming.radionomy.html
// ---------------------------------------
!function(){function a(a){function b(b){if(b){var d=b.tracks;if(d&&j!=d.uniqueid){var e=d.artist||d.artists;"RADIONOMY"!=e&&"Targetspot"!=e||(d.title=o,d.artist=p),j=d.uniqueid;var f=!1,g=d.cover||d.image;g!=q&&(k.setCoverArt(g),q=g,f=!0);var h=!1;if((d.title||e||d.album)&&(h=!0,k.setInfo({title:d.title,artist:d.artist||d.artists,album:d.album}),i=d.title),(f||h)&&a.onChangeTrack&&a.onChangeTrack({title:d.title,artist:d.artist||d.artists,album:d.album,image:g}),d.pixel){if(!l){var m=document.createElement("img");m.width=1,m.height=1;var n=document.getElementById("body");n&&(n.appendChild(m),l=m)}l&&(l.src=d.pixel)}var r=Number(d.callmeback),s=Number(d.playduration),t=s>r?r:s;!t||0>t||t==1/0||NaN==t?t=5e3:t>2e5&&(t=2e5),c(t)}}}function c(a,b){var c=parseInt(a)||n;m&&clearInterval(m),b!==!0&&1e3>c&&(c=1e3),m=setInterval(d,c)}function d(){var a=h.apiURL+"?",b=[];for(var c in h)"url"!=c&&"apiURL"!=c&&b.push(c+"="+h[c]);a+=b.join("&"),new jbeeb.JSON_P(a,function(){})}function e(){j=null,c(100,!0)}function f(){m&&clearInterval(m),k.setPlaylist([{file:a.listenURL+"?"+jbeeb.Utils.getTimestamp(),kind:"mp3",title:p}]),k.next(),k.stop(!0)}function g(){window.GetPlayInfo=b,k||(k="string"==typeof a.player?wimpy.getPlayer(a.player):a.player),k.setPlaylist([{file:a.listenURL+"?"+jbeeb.Utils.getTimestamp(),kind:"mp3",title:p}]),k.addEventListener("play",e),k.addEventListener("pause",f),a.startOnLoad&&k.play()}var h={apiURL:a.apiURL||"http://api.radionomy.com/currentsong.cfm",radiouid:a.guid,apikey:a.apikey,type:"json",callmeback:"yes",type:"json",cover:"yes",previous:"no"},i=null,j=-1,k=null,l=null,m=null,n=a.pollFrequency||10,o=a.adTitle||"Advertisement",p=a.listenTitle||"",q=null;wimpy.onReady(g)}window.StreamInfoRadionomy||(window.StreamInfoRadionomy=a)}();